site_name: "Ontology-Metadata"
theme:
  name: material
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
#  - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://stroemphi.github.io/Ontology-Metadata
repo_url: https://github.com/stroemphi/Ontology-Metadata

# Uncomment this block to enable use of Google Analytics. 
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
